services:
    dbserver:
        image: proyectocloud.azurecr.io/marketplace/mongo
        container_name: dbserver
        ports:
            - 27000:27017
        networks:
            - marketplace
    eureka:
        image: proyectocloud.azurecr.io/marketplace/erueka
        build: ./eurekaserver
        container_name: eureka
        ports:
            - 18761:8761
        networks:
            - marketplace

    authentication:
        image: proyectocloud.azurecr.io/marketplace/authentication
        build: ./Authentication
        networks:
            - marketplace
        ports:
            - "11100:11100"
networks:
    marketplace:
        driver: bridge
volumes:
    mongodb-data: